### PR TITLE
Add new SliderAnt component

### PR DESCRIPTION
**Pull request by csillag**

### CODE REVIEW

**Review by scharf — COMMENTED** [review]
The number shown left of the slider seems to be aligned wrongly and on smaller screens it overlaps with the slider....
image


Why not using a input field for the slider like in the https://ant.design/components/slider/ example?

image

**Comment by csillag** [comment]
My first iteration was exactly like that (ie. with an input field), but it was more trouble than it was worth. (Ie. pressing the up or down buttons jumped to weird values, even though I have passed in the "step" parameter...) In the end I decided that it's not worth it.

The layout issues should be solved by the proper usage of the AntD `<Row>` and `<Col>` components.... maybe it's time to me to least how to build a proper reactive grid in Ant?

**Review by scharf — APPROVED** [review]
LGTM

**Comment by scharf** [comment]
I think its good enough for  now

**Pull request merged**
