### PR TITLE
[WIP, demo only] Native routing

### PR DESCRIPTION
**Pull request by csillag**
This is a version of the routing PR (https://github.com/moxb/moxb/pull/41) which supports "native" routing, that is, putting the path into the actual path (like `http://localhost:1234/loginForm`), as opposed to the (more widely compatible) query-based routing (like `http://localhost:1234/index.html?path=loginForm`)

The downside is that this way we can't serve multiple HTML files at once (with parcel), so we can't run the SemUI and the AntD demo at the same time. Currently, only the AntD version is run.

### CODE REVIEW

**Comment by csillag** [comment]
I have rebased this to the top of the latest routing branch, so that it has all the features.

**Comment by scharf** [comment]
do we need this branch or can it be deleted?

**Comment by csillag** [comment]
Now I reduced this branch to a single commit.
I think it's useful to have it around, for when we need to test the native URL scheme.

**Comment by Herndl** [comment]
@csillag Is this PR still in progress, or can we close it?

**Comment by csillag** [comment]
We can close the PR, but please don't kill the branch. It can be useful as a reference to see how to implement this. (Which is unfeasible in the main example.)

**Pull request closed without merging**
